name: checks

on:
  pull_request:
    types: [opened, synchronize, reopened, edited, ready_for_review]
  merge_group:
  push:
    branches: [main]

permissions:
  contents: read

concurrency:
  group: checks-${{ github.ref }}
  cancel-in-progress: true

jobs:
  checks:
    if: github.event.pull_request.draft != true
    uses: Sneakers-PAM/.github/.github/workflows/scrub.yml@main
